
	
	</div><!-- /content -->
	
	
	<div id="footer">
		<p>
			Copyright &copy; 2014 Muhire Kavuna. All rights reserved.<br />
			<span class="subtext">
				Developed by Muhire Kavuna
			</span>        
		</p>
	</div><!-- /footer -->

</div><!-- /page -->



<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
</body>
</html>
